# Generated by Django 5.2.1 on 2025-07-18 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paymentreceipt'),
        ('registration', '0005_alter_visit_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='registration.visit'),
        ),
    ]
