# Generated by Django 5.2.1 on 2025-07-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_bill_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='custom_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='discount_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='discounted',
            field=models.BooleanField(default=False),
        ),
    ]
