# Generated by Django 5.2.1 on 2025-08-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_bill_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed'), ('refunded', 'Refunded'), ('partially_paid', 'Partially Paid'), ('overpaid', 'Overpaid'), ('underpaid', 'Underpaid'), ('voided', 'Voided'), ('failed', 'Failed'), ('authorized', 'Authorized'), ('requires_authorization', 'Requires Authorization'), ('processing', 'Processing'), ('completed', 'Completed'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('reversed', 'Reversed'), ('chargeback', 'Chargeback'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('pending_refund', 'Pending Refund')], default='pending', max_length=200),
        ),
    ]
