# Generated by Django 5.2.1 on 2025-08-07 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_paymentreceipt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='amount',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
