# Generated by Django 5.2.1 on 2025-09-03 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_paymentreceipt_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
