# Generated by Django 5.2.1 on 2025-12-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashaccount',
            old_name='account_type',
            new_name='category',
        ),
    ]
