# Generated by Django 5.2.1 on 2025-12-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_account_type_cashaccount_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashaccount',
            old_name='sub_account_type',
            new_name='sub_category',
        ),
    ]
