# Generated by Django 5.2.1 on 2025-12-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_sub_account_type_cashaccount_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashaccount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
