# Generated by Django 5.2.1 on 2025-08-13 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_cashaccount'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_hospital', to='hospital.hospital'),
        ),
    ]
