# Generated by Django 5.2.1 on 2025-12-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_cashaccount_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
    ]
