# Generated by Django 5.2.1 on 2025-12-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_cashaccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='category',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='currency',
            field=models.CharField(default='KES', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='financial_statement_category',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='sub_category',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
