# Generated by Django 5.2.1 on 2025-12-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_cashaccount_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='account_type',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Account'), ('cash', 'Cash in Hand'), ('mobile', 'Mobile Money'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
