# Generated by Django 5.2.1 on 2025-07-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='requisition_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
