# Generated by Django 5.2.1 on 2025-12-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_cashaccount_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashaccount',
            name='description',
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='category',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='financial_statement_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
