# Generated by Django 5.2.1 on 2025-07-22 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_requisition_requisition_id'),
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(help_text='Asset ID or code', max_length=100)),
                ('asset_class', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('additions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('disposal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_asset', models.DecimalField(decimal_places=2, max_digits=15)),
                ('opening_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('depreciation_year', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('depreciation_deletion', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_depreciation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_book_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FixedAssets_done', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='hospital.hospital')),
            ],
        ),
    ]
