# Generated by Django 5.2.1 on 2025-12-02 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_cashaccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='account_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
