# Generated by Django 5.2.1 on 2025-12-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_cashaccount_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycashentry',
            name='Acc_no',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='Acc_type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='Document_no',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='Document_type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='External_document_no',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='balance_acc_no',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='balance_acc_type',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='branch_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='credit_ledger_account',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='debit_ledger_account',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='department_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='line_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
