# Generated by Django 5.2.1 on 2025-12-02 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_cashaccount_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettycashentry',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='pettycashentry',
            name='paid_to',
        ),
        migrations.RemoveField(
            model_name='pettycashentry',
            name='received_by',
        ),
        migrations.AddField(
            model_name='pettycashentry',
            name='ledger_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_ledger_entry', to='finance.ledgerentry'),
        ),
    ]
