# Generated by Django 5.2.1 on 2025-12-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_pettycashentry_acc_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pettycashentry',
            old_name='Acc_no',
            new_name='acc_no',
        ),
        migrations.RenameField(
            model_name='pettycashentry',
            old_name='Acc_type',
            new_name='acc_type',
        ),
        migrations.RenameField(
            model_name='pettycashentry',
            old_name='Document_date',
            new_name='document_date',
        ),
        migrations.RenameField(
            model_name='pettycashentry',
            old_name='Document_no',
            new_name='document_no',
        ),
        migrations.RenameField(
            model_name='pettycashentry',
            old_name='Document_type',
            new_name='document_type',
        ),
        migrations.RenameField(
            model_name='pettycashentry',
            old_name='External_document_no',
            new_name='external_document_no',
        ),
        migrations.AddField(
            model_name='pettycashentry',
            name='entry_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
