# Generated by Django 5.2.1 on 2025-12-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_remove_pettycashentry_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettycashentry',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
