# Generated by Django 5.2.1 on 2025-12-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_rename_acc_no_pettycashentry_acc_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashaccount',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
