# Generated by Django 5.2.1 on 2025-12-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_cashaccount_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettycashentry',
            name='entry_type',
        ),
    ]
