# Generated by Django 5.2.1 on 2025-12-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_pettycashentry_ledger_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashaccount',
            name='financial_statement_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='sub_account_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
