# Generated by Django 5.2.1 on 2025-12-05 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_cashaccount_financial_statement_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashentry',
            name='Acc_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pettycashentry',
            name='Acc_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pettycashentry',
            name='Document_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pettycashentry',
            name='Document_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pettycashentry',
            name='Document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pettycashentry',
            name='External_document_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='entry_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='ledger_account',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
