# Generated by Django 5.2.1 on 2025-12-10 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_remove_pettycashentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycashentry',
            name='credit_ledger_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_entries', to='finance.cashaccount'),
        ),
        migrations.AlterField(
            model_name='pettycashentry',
            name='debit_ledger_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_entries', to='finance.cashaccount'),
        ),
    ]
