# Generated by Django 5.2.1 on 2025-05-28 15:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('bp_dia', models.IntegerField(blank=True, help_text='Diastolic blood pressure (mmHg)', null=True)),
                ('bp', models.IntegerField(blank=True, help_text='Systolic blood pressure (mmHg)', null=True)),
                ('pr', models.IntegerField(blank=True, help_text='Pulse rate (bpm)', null=True)),
                ('spo2', models.FloatField(blank=True, help_text='Oxygen saturation (%)', null=True)),
                ('rbs', models.FloatField(blank=True, help_text='Random blood sugar (mmol/L)', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Body temperature (°C)', null=True)),
                ('height', models.FloatField(blank=True, help_text='Height (cm)', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight (kg)', null=True)),
                ('bmi', models.FloatField(blank=True, help_text='Body Mass Index', null=True)),
                ('body_fat', models.FloatField(blank=True, help_text='Body fat percentage (%)', null=True)),
                ('muscle_mass', models.FloatField(blank=True, help_text='Muscle mass (kg)', null=True)),
                ('bone_mass', models.FloatField(blank=True, help_text='Bone mass (kg)', null=True)),
                ('metabo_age', models.IntegerField(blank=True, help_text='Metabolic age', null=True)),
                ('calories', models.IntegerField(blank=True, help_text='Calories burned per day (kcal)', null=True)),
                ('visce', models.IntegerField(blank=True, help_text='Visceral fat level', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triages', to=settings.AUTH_USER_MODEL)),
                ('recorder_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_recordings', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triages', to='registration.visit')),
            ],
        ),
    ]
