# Generated by Django 5.2.1 on 2025-09-08 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='triage',
            old_name='bp',
            new_name='bp_sys',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='body_fat',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='bone_mass',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='metabo_age',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='muscle_mass',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='visce',
        ),
        migrations.AlterField(
            model_name='triage',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage', to=settings.AUTH_USER_MODEL),
        ),
    ]
