# Generated by Django 5.2.1 on 2025-07-22 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text="A short internal code like 'jubilee', 'aar'", max_length=20, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('requires_authorization', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, verbose_name='Card/Membership Number')),
                ('scheme_type', models.CharField(max_length=100, verbose_name='Scheme Type (Inpatient/Outpatient)')),
                ('principal_name', models.CharField(max_length=100, verbose_name='Principal Member Name')),
                ('relationship_to_principal', models.CharField(max_length=50, verbose_name='Relationship to Principal')),
                ('employer_name', models.CharField(blank=True, max_length=100)),
                ('employer_code', models.CharField(blank=True, max_length=50)),
                ('nhif_number', models.CharField(blank=True, max_length=50)),
                ('nhif_contribution_proof', models.FileField(blank=True, null=True, upload_to='nhif_proofs/')),
                ('pre_authorization_code', models.CharField(blank=True, max_length=100)),
                ('authorization_letter', models.FileField(blank=True, null=True, upload_to='auth_letters/')),
                ('authorization_date', models.DateField(blank=True, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_records', to=settings.AUTH_USER_MODEL)),
                ('insurance_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='accounts.insuranceprovider')),
            ],
        ),
    ]
