# Generated by Django 5.2.1 on 2025-07-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_insuranceprovider_insuranceinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceinformation',
            name='scheme_type',
            field=models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient'), ('in_and_out', 'Inpatient & Outpatient'), ('none', 'None')], max_length=20, verbose_name='Scheme Type'),
        ),
    ]
