# Generated by Django 5.2.1 on 2025-07-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_insuranceinformation_scheme_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceinformation',
            old_name='nhif_contribution_proof',
            new_name='sha_contribution_proof',
        ),
        migrations.RenameField(
            model_name='insuranceinformation',
            old_name='nhif_number',
            new_name='sha_number',
        ),
    ]
