# Generated by Django 5.2.1 on 2025-07-22 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_nhif_contribution_proof_insuranceinformation_sha_contribution_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceinformation',
            name='insurance_provider',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='accounts.insuranceprovider'),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='sha_contribution_proof',
            field=models.FileField(blank=True, null=True, upload_to='shif_proofs/'),
        ),
    ]
