# Generated by Django 5.2.1 on 2025-07-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_insuranceinformation_insurance_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
