# Generated by Django 5.2.1 on 2025-07-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID or Passport Number', max_length=20, null=True, unique=True),
        ),
    ]
