# Generated by Django 5.2.1 on 2025-07-24 09:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient'), ('minor_surgery', 'Minor_surgery'), ('outpatient_consultation', 'Outpatient (Consultation)')], default='outpatient', help_text='Type of visit: Inpatient or Outpatient', max_length=30)),
                ('tracking_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('triage', 'Triage'), ('doctor', 'Doctor'), ('note', 'Note'), ('consultation', 'Consultation'), ('laboratory', 'Laboratory'), ('prescription', 'Prescription'), ('billing', 'Billing(From Registration)'), ('billing_note', 'Billing (From Note)'), ('billing_prescription', 'Billing (From Prescription)'), ('billing_pharmacy', 'Billing (From Pharmacy)'), ('pharmacy', 'Pharmacy'), ('inpatient', 'Inpatient'), ('discharged', 'Discharged')], max_length=30)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='hospital.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
