# Generated by Django 5.2.1 on 2025-05-28 15:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('stage', models.CharField(choices=[('triage', 'Triage'), ('note', 'Note'), ('laboratory', 'Laboratory'), ('prescription', 'Prescription'), ('billing', 'Billing'), ('pharmacy', 'Pharmacy'), ('inpatient', 'Inpatient'), ('discharged', 'Discharged')], max_length=20)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='hospital.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
