# Generated by Django 5.2.1 on 2025-11-04 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctornote_chief_complains'),
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='stage',
            field=models.CharField(choices=[('triage', 'Triage'), ('doctor', 'Doctor'), ('note', 'Note'), ('consultation', 'Consultation'), ('laboratory', 'Laboratory'), ('prescription', 'Prescription'), ('billing', 'Billing(From Registration)'), ('billing_note', 'Billing (From Note)'), ('billing_prescription', 'Billing (From Prescription)'), ('billing_pharmacy', 'Billing (From Pharmacy)'), ('pharmacy', 'Pharmacy'), ('inpatient', 'Inpatient'), ('discharged', 'Discharged'), ('referral', 'Referral')], max_length=30),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('referred_to_hospital', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctornote')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='registration.visit')),
            ],
        ),
    ]
