# Generated by Django 5.2.1 on 2025-06-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_visit_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='stage',
            field=models.CharField(choices=[('triage', 'Triage'), ('doctor', 'Doctor'), ('note', 'Note'), ('laboratory', 'Laboratory'), ('prescription', 'Prescription'), ('billing', 'Billing'), ('pharmacy', 'Pharmacy'), ('inpatient', 'Inpatient'), ('discharged', 'Discharged')], max_length=20),
        ),
    ]
