# Generated by Django 5.2.1 on 2025-11-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_visit_stage_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='stage',
            field=models.CharField(choices=[('triage', 'Triage'), ('doctor', 'Doctor'), ('note', 'Note'), ('consultation', 'Consultation'), ('laboratory', 'Laboratory'), ('prescription', 'Prescription'), ('billing', 'Billing(From Registration)'), ('billing_note', 'Billing (From Note)'), ('billing_prescription', 'Billing (From Prescription)'), ('billing_pharmacy', 'Billing (From Pharmacy)'), ('pharmacy', 'Pharmacy'), ('inpatient', 'Inpatient'), ('discharged', 'Discharged'), ('referral', 'Referral'), ('admitted', 'Admitted')], max_length=30),
        ),
    ]
