# Generated by Django 5.2.1 on 2025-07-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_visit_updated_on_alter_visit_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='stage',
            field=models.CharField(choices=[('triage', 'Triage'), ('doctor', 'Doctor'), ('note', 'Note'), ('laboratory', 'Laboratory'), ('prescription', 'Prescription'), ('billing_note', 'Billing (From Note)'), ('billing_prescription', 'Billing (From Prescription)'), ('billing_pharmacy', 'Billing (From Pharmacy)'), ('pharmacy', 'Pharmacy'), ('inpatient', 'Inpatient'), ('discharged', 'Discharged')], max_length=30),
        ),
        migrations.AlterField(
            model_name='visit',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
