# Generated by Django 5.2.1 on 2025-07-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_visit_stage_alter_visit_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='stage',
            field=models.CharField(choices=[('triage', 'Triage'), ('doctor', 'Doctor'), ('note', 'Note'), ('laboratory', 'Laboratory'), ('prescription', 'Prescription'), ('billing', 'Billing(From Registration)'), ('billing_note', 'Billing (From Note)'), ('billing_prescription', 'Billing (From Prescription)'), ('billing_pharmacy', 'Billing (From Pharmacy)'), ('pharmacy', 'Pharmacy'), ('inpatient', 'Inpatient'), ('discharged', 'Discharged')], max_length=30),
        ),
    ]
