# Generated by Django 5.2.1 on 2025-07-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_visit_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='type',
            field=models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient')], default='outpatient', help_text='Type of visit: Inpatient or Outpatient', max_length=30),
        ),
        migrations.AlterField(
            model_name='visit',
            name='stage',
            field=models.CharField(choices=[('triage', 'Triage'), ('doctor', 'Doctor'), ('note', 'Note'), ('consultation', 'Consultation'), ('laboratory', 'Laboratory'), ('prescription', 'Prescription'), ('billing', 'Billing(From Registration)'), ('billing_note', 'Billing (From Note)'), ('billing_prescription', 'Billing (From Prescription)'), ('billing_pharmacy', 'Billing (From Pharmacy)'), ('pharmacy', 'Pharmacy'), ('inpatient', 'Inpatient'), ('discharged', 'Discharged')], max_length=30),
        ),
    ]
