# Generated by Django 5.2.1 on 2025-07-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_visit_type_alter_visit_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='type',
            field=models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient'), ('minor_surgery', 'Minor_surgery'), ('outpatient_consultation', 'Outpatient (Consultation)')], default='outpatient', help_text='Type of visit: Inpatient or Outpatient', max_length=30),
        ),
    ]
