# Generated by Django 5.2.1 on 2025-05-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_prescriptionnote'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornote',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='doctor_notes', to='laboratory.test'),
        ),
    ]
