# Generated by Django 5.2.1 on 2025-09-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_icd10entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornote',
            name='icd10_codes',
            field=models.ManyToManyField(blank=True, related_name='doctor_notes', to='doctor.icd10entry'),
        ),
        migrations.AlterField(
            model_name='doctornote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
