# Generated by Django 5.2.1 on 2025-09-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctornote_icd10_codes_alter_doctornote_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornote',
            name='icd10_codes',
            field=models.ManyToManyField(blank=True, help_text='Select one or more ICD-10 codes (any level: chapter, block, category, subcategory).', related_name='doctor_notes', to='doctor.icd10entry'),
        ),
    ]
