# Generated by Django 5.2.1 on 2025-09-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctornote_icd10_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornote',
            name='chief_complains',
            field=models.TextField(blank=True, help_text='List of chief complaints (bullet format).', null=True),
        ),
    ]
